version: '2.2'
services:
  server:
    build:
      context: ./container-build
      dockerfile: webserver.dockerfile
    container_name: projetos.server
    environment:
      - ALLOW_OVERRIDE=all
      - XDEBUG_CONFIG=remote_host=127.0.0.1
      - PHP_IDE_CONFIG=serverName=projetos.xdebug
    ports:
      - '80:80'
      - '443:443'
      - '9001:9001'
    links:
      - db
    volumes:
      - '/Users/renato/workspace/projetos/sites:/var/www/html'
      - '/Users/renato/workspace/projetos/server/php/ext/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - '/Users/renato/workspace/projetos/server/apache/sites-available:/etc/apache2/sites-available'
      - '/Users/renato/workspace/projetos/server/apache/sites-enabled:/etc/apache2/sites-enabled'
    restart: always

  composer:
    container_name: projetos.composer
    image: composer/composer
    volumes_from:
      - server
    working_dir: /var/www/html
    restart: always
    
  db:
    image: mysql:5.7
    container_name: projetos.db
    environment:
      - MYSQL_ROOT_PASSWORD=projetos212223
      - MYSQL_USER=renato
      - MYSQL_PASSWORD=renato
    ports:
      - '3306:3306'
    volumes:
      - /Users/renato/workspace/projetos/server/mysql/config:/etc/mysql
      - /Users/renato/workspace/projetos/server/mysql/data:/var/lib/mysql
    restart: always